version: '3'

services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx
        # маршрутизируем порты
        ports:
            - "8080:80"
            - "8443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql
        ports:
            - "8306:3306"
        volumes:
         - ./mysql-conf:/etc/mysql
         #- ./logs/mysql:/var/log/mysql
         - ./mysql:/var/lib/mysql
         - ./mysql-files:/var/lib/mysql-files
         #- ./data:/docker-entrypoint-initdb.d
        # задаем пароль для root пользователя
        # заливку дампа сайта и создание пользователя для доступа к базе снаружи будем делать позже
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test_php
    redis:
        image: redis
        ports:
            - "6379:6379"